version: "3.8"

services:
  nginx-gateway:
    image: nginx-gateway:latest
    container_name: nginx-gateway
    user: "$UID:$GID"
    ports:
      - "8080:8080"
    volumes:
      - ./insights-core:/usr/share/nginx/html/static/release:Z
      - ./certs:/etc/nginx/certs:Z
      - ./sockets:/sockets:Z
      - ./nginx.conf:/etc/nginx/nginx.conf:Z
    networks:
      - gateway-network
    depends_on:
      - advisor-api
      - inventory-api
      - app

  advisor-api:
    image: registry.access.redhat.com/ubi9/python-311:latest
    container_name: advisor-api
    command: ["python", "/mock.py"]
    environment:
      - MOCK_NAME=advisor-api
    volumes:
      - ./mock-advisor.py:/mock.py:Z
    networks:
      - gateway-network

  inventory-api:
    image: registry.access.redhat.com/ubi9/python-311:latest
    container_name: inventory-api
    command: ["python", "/mock.py"]
    environment:
      - MOCK_NAME=inventory-api
    volumes:
      - ./mock-inventory.py:/mock.py:Z
    networks:
      - gateway-network

  app:
    image: registry.access.redhat.com/ubi9/python-311:latest
    container_name: app
    command: ["python", "/mock.py"]
    environment:
      - MOCK_NAME=app
    volumes:
      - ./mock-app.py:/mock.py:Z
    networks:
      - gateway-network

networks:
  gateway-network:
    name: gateway-network
  